### ISSUE TITLE
Cannot override root directory's .node-version with .nvmrc

### ISSUE THREAD

**Issue by lumaxis** [ouchxp/nodenv-nvmrc#7]
>nodenv traverses the file hierarchy upwards until it finds a `.node-version` file or falls back to `~/.nodenv/version`, if that exists.
>That means I can't override either a root directory's Node version or my global version via a local `.nvmrc` file because of this skip.

_Originally posted by @lumaxis in https://github.com/ouchxp/nodenv-nvmrc/issues/5#issuecomment-663302766_

I think the problem here is `should_find_in_nvmrc()` because for a use case like mine, `nodenv local` will return the root folder's version from `../.node_version`.

**Comment by ouchxp** [comment]
Hi @lumaxis , thanks for raising the issue! I will work on it tonight

**Comment by lumaxis** [comment]
Thanks! 🙏🏼

**Comment by lumaxis** [comment]
Adding the `nodenv local` usage description since that also explains why this problem exists:
>When you run a Node command, nodenv will look for a `.node-version`
file in the current directory and each parent directory. If no such
file is found in the tree, nodenv will use the global Node version
specified with `nodenv global`. A version specified with the
`NODENV_VERSION` environment variable takes precedence over local
and global versions

**Comment by ouchxp** [comment]
Hi @lumaxis  Release 1.0.5 should have fixed. Please let me know if it works for you 🙏

**Comment by lumaxis** [comment]
Yes, looks great! Thank you very much for fixing it so quickly 🙌🏼 ✨
